### ISSUE TITLE
make fails due to missing ctr_drbg_free function

### ISSUE THREAD

**Issue by neerolyte** [hugsy/proxenet#38]
```
$ make
[  8%] Building C object CMakeFiles/proxenet.dir/ssl.c.o
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined [enabled by default]
<built-in>:0:0: note: this is the location of the previous definition
.../proxenet/ssl.c: In function ‘proxenet_ssl_free_structs’:
.../proxenet/ssl.c:367:9: error: implicit declaration of function ‘ctr_drbg_free’ [-Werror=implicit-function-declaration]
         ctr_drbg_free( &ssl->ctr_drbg );
         ^
cc1: some warnings being treated as errors
make[2]: *** [CMakeFiles/proxenet.dir/ssl.c.o] Error 1
make[1]: *** [CMakeFiles/proxenet.dir/all] Error 2
make: *** [all] Error 2
```

I'm using a version of polarssl that appears to match the doco at https://proxenet.readthedocs.org/en/latest/compil/ : 
```
$ dpkg --status libpolarssl-dev | grep ^Version
Version: 1.3.4-1
``` 

Looking through historical tags for mbedtls, it looks like that function only appeared in 1.3.8 though.

**Comment by hugsy** [comment]
PolarSSL packaged in 1.3.4 ? 

Which distro is that?

**Comment by neerolyte** [comment]
Good point :p 

Ubuntu 14.04.3 LTS

**Comment by hugsy** [comment]
Will look, thanks.

**Comment by srozb** [comment]
crashing on 14.04, but compiles fine with 15.10 (dockerized).

**Comment by hugsy** [comment]
Wow, totally forgot about that :-)

I will pop up a Ubuntu 14.04 VM today and try it, but I totally dropped the support for `polarssl` < 2.x for the unstable version of `proxenet` due to too many changes in the `polarssl` API (which is not even called `polarssl` but `mbedtls` since 2 years). This new version should be released soon.

Ubuntu 14 does not offer support for it so I would recommend upgrading altogether anyway.

**Comment by hugsy** [comment]
Closing this issue since 0.4 is out, totally abandonning support for PolarSSL (only supports MbedTLS >= 2.x). 

No backport will be made.
